name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install g++11
      run: sudo apt install gcc-11 g++-11
    - name: build libsodium
      run: make build-libsodium
    - name: make
      run: make
    - name: run tests
      run: ./Buffer
